name: StabiliserSuite
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - qiskit>=1.3
  - numpy>=2.2.0
  - matplotlib>=3.10.0
  - pylatexenc>=2.10
  - pytest-runner
  - tox>=4.23.2
  - coverage>=7.6.9
  - numba
  - tqdm
  - pandas
