name: Release
on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASER_APP }}
          private_key: ${{ secrets.RELEASER_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          semantic-release publish